using AtividadePratica;
using System;
//DiaDaSemana.Main(args);
//OperacoesAritmeticas.Main(args);
//ClassificaçãoDeIdade.Main(args);
//MenuDeOpções.Main(args);
//NotaDoAluno.Main(args);
//EscolhaDeBebida.Main(args);
//CalculadoraDeImpostos.Main(args);
ConversorDeTemperatura.Main(args);
//CategoriaDeFilme.Main(args);
//CalculadoraDeFatorial.Main(args);